apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/taskmanagementdb"
  SPRING_MAIL_HOST: "smtp.gmail.com"
  SPRING_MAIL_PORT: "587"