apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  # Use base64 encoding for the values:
  # echo -n 'your_username' | base64
  SPRING_DATASOURCE_USERNAME: cG9zdGdyZXM=
  # echo -n 'your_database_password' | base64
  SPRING_DATASOURCE_PASSWORD: b2Nob2xhbW8x
  # echo -n 'your_email_username' | base64
  SPRING_MAIL_USERNAME: bW92aW5lZWVAZ21haWwuY29t
  # echo -n 'your_email_password' | base64
  SPRING_MAIL_PASSWORD: b2Nob2xhbW8x