apiVersion: v1
kind: Service
metadata:
  name: task-management-system-service
spec:
  selector:
    app: task-management-system
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer